version: "3.8"

networks:
  vpn:
    external: true
    name: vpn

services:
  wireguard:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=PUBLICIPHERE

      # ⚠️ Change the Web UI Password:
      - PASSWORD=pToPTF8Qi5MdtSyZIk

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x

      # https://docs.pi-hole.net/guides/vpn/wireguard/internal/
      - WG_POST_UP=iptables -w -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_DOWN=iptables -w -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      - WG_ALLOWED_IPS=0.0.0.0/0,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    image: weejewel/wg-easy
    container_name: wireguard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./wireguard-data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "PORTHERE:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    #labels:
      #caddy: DOMAINSUBNAMEHERE
      #caddy.reverse_proxy: "IPADDRESSHERE:PORTHERE"
      #traefik.enable: true
      #traefik.http.routers.wireguard.entrypoints: web,websecure
      #traefik.http.routers.wireguard.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.wireguard.tls: true
      #traefik.http.routers.wireguard.tls.certresolver: production
      #traefik.http.services.wireguard.loadbalancer.server.port: PORTHERE
      #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
      #traefik.http.routers.wireguard.middlewares: my-whitelist-in-docker@docker
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE