version: "3.8"

networks:
  vpn:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - PORT1:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #labels:
      #caddy: DOMAINSUBNAMEHERE
      #caddy.reverse_proxy: IPADDRESSHERE:PORT1
      #traefik.enable: true
      #traefik.http.routers.prometheus.entrypoints: web,websecure
      #traefik.http.routers.prometheus.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.prometheus.tls: true
      #traefik.http.routers.prometheus.tls.certresolver: production
      #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
      #traefik.http.routers.prometheus.middlewares: my-whitelist-in-docker@docker
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
