version: '3.9'

networks:
  vpn:
    external: true

services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - 'PORT1:80'
    volumes:
    - /docker/ssh/public:/usr/local/apache2/htdocs
    networks:
      vpn:
         ipv4_address: IPADDRESSHERE
