version: "2"

networks:
  vpn:
    external: true

services:
  ipinfo:
    container_name: ipinfo
    image: peterdavehello/ipinfo.tw:latest
    restart: unless-stopped
    ports:
      - PORTHERE:8080
    #labels:
      #caddy: DOMAINSUBNAMEHERE
      #caddy.reverse_proxy: IPADDRESSHERE:PORTHERE
      #traefik.enable: true
      #traefik.http.routers.ipinfo.entrypoints: web,websecure
      #traefik.http.routers.ipinfo.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.ipinfo.tls: true
      #traefik.http.routers.ipinfo.tls.certresolver: production
      #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
      #traefik.http.routers.ipinfo.middlewares: my-whitelist-in-docker@docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
