version: '3.7'

networks:
  vpn:
    external: true

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
     - PORTHERE:8080
    restart: unless-stopped
    volumes:
      - ./searxng-data/:/etc/searxng:rw
    #environment:
      #- SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      #caddy: DOMAINSUBNAMEHERE
      #caddy.reverse_proxy: IPADDRESSHERE:PORTHERE
      #traefik.enable: true
      #traefik.http.routers.searxng.entrypoints: web,websecure
      #traefik.http.routers.searxng.rule: Host(`DOMAINSUBNAMEHERE`) # Update to your domain
      #traefik.http.routers.searxng.tls: true
      #traefik.http.routers.searxng.tls.certresolver: production
    networks:
      vpn:
         ipv4_address: IPADDRESSHERE