version: "3.3"

networks:
  vpn:
    external: true

services:
  speedtest:
    image: adolfintel/speedtest
    container_name: speedtest
    environment:
      - MODE=standalone
      - TELEMETRY=false
      - ENABLE_ID_OBFUSCATION=true
      - PASSWORD=asGA5sa9ajsomtf
      - WEBPORT=80
    ports:
      - 4001:80
    #labels:
      #caddy: DOMAINSUBNAMEHERE
      #caddy.reverse_proxy: IPADDRESSHERE:PORT1
      #traefik.enable: true
      #traefik.http.routers.speedtest.entrypoints: web,websecure
      #traefik.http.routers.speedtest.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.speedtest.tls: true
      #traefik.http.routers.speedtest.tls.certresolver: production
      #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
      #traefik.http.routers.speedtest.middlewares: my-whitelist-in-docker@docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
