version: '3'

networks:
  vpn:
    external: true

services:
    nginx-mailcow:
      container_name: mailcow
      networks:
        vpn:
          ipv4_address: IPADDRESSHERE
      #labels:
        #traefik.enable: true
        #traefik.http.routers.moo.rule: Host(`${MAILCOW_HOSTNAME}`)
        #traefik.http.routers.moo.tls: true
        #traefik.http.routers.moo.tls.certresolver: production
        #traefik.http.services.moo.loadbalancer.server.port: PORT1
        #traefik.http.routers.moo.entrypoints: websecure
        #traefik.docker.network: DOCKERNETWORK
        #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
        #traefik.http.routers.moo.middlewares:
