version: "3.8"

networks:
  vpn:
    external: true
    name: vpn

services:
  virtualminwebhost:
    container_name: "virtualminwebhost"
    image: qoomon/docker-host
    restart: always
    cap_add: ["NET_ADMIN", "NET_RAW"]
    #labels:
      #traefik.enable: true
      #traefik.http.routers.virtualminwebhost.entrypoints: web,websecure
      #traefik.http.routers.virtualminwebhost.rule: Host(`DOMAINNAMEHERE`)
      #traefik.http.routers.virtualminwebhost.tls: true
      #traefik.http.routers.virtualminwebhost.tls.certresolver: production
      #traefik.http.services.virtualminwebhost.loadbalancer.server.port: PORT1
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
