version: '3.2'
networks:
  vpn:
    external: true
services:
  killbill:
    image: killbill/killbill:0.24.0
    container_name: killbill
    ports:
      - "8788:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
    networks:
      vpn:
        ipv4_address: 10.8.1.111
  kaui:
    image: killbill/kaui:2.0.11
    container_name: killbill_ui
    ports:
      - "PORTHERE:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
    #labels:
      #caddy: DOMAINSUBNAMEHERE
      #caddy.reverse_proxy: "IPADDRESSHERE:PORTHERE"
      #traefik.enable: true
      #traefik.http.routers.killbill.entrypoints: web,websecure
      #traefik.http.routers.killbill.rule: Host(`DOMAINSUBNAMEHERE`) # Update to your domain
      #traefik.http.routers.killbill.tls: true
      #traefik.http.routers.killbill.tls.certresolver: production
      #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
      #traefik.http.routers.killbill.middlewares: my-whitelist-in-docker@docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
  db:
    image: killbill/mariadb:0.24
    container_name: killbill_db
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
    networks:
      vpn:
        ipv4_address: 10.8.1.112