version: "3"

networks:
  vpn:
    external: true
    name: vpn

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc:/etc/traefik
    #labels:
      #caddy: DOMAINSUBNAMEHERE
      #caddy.reverse_proxy: IPADDRESSHERE:PORTHERE
      #traefik.enable: true
      #traefik.http.routers.traefik.entrypoints: web,websecure
      #traefik.http.routers.traefik.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.traefik.tls: true
      #traefik.http.routers.traefik.tls.certresolver: production
      #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
      #traefik.http.routers.traefik.middlewares: my-whitelist-in-docker@docker
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE