version: "3"

networks:
  vpn:
    external: true
    name: vpn

services:
  traefik:
    image: traefik:v2.10.5
    container_name: traefik
    ports:
      - PORT1:80
      - PORT2:443
      - PORT3:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc:/etc/traefik
    #labels:
      #traefik.docker.network: DOCKERNETWORK
      #traefik.enable: "true"
      #traefik.http.routers.traefik.entrypoints: web,websecure
      #traefik.http.routers.traefik.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.traefik.service: api@internal
      #traefik.http.routers.traefik.tls: true
      #traefik.http.routers.traefik.tls.certresolver: production
      #traefik.http.services.traefik.loadbalancer.server.port: PORT3
      #traefik.http.middlewares.my-whitelist-in-docker.ipwhitelist.sourcerange: IPWHITELIST
      #traefik.http.routers.traefik.middlewares:
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
