version: "3"

networks:
  vpn:
    external: true
    name: vpn

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc:/etc/traefik
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE